### PR TITLE
Update from MVC to Phoenix 1.3 contexts

### PR DESCRIPTION
**Pull request by nunopolonia**
- Update elixir version
- Update config to Phoenix 1.3 standards
- Update MVC to Phoenix 1.3 contexts

### CODE REVIEW

**Comment by nunopolonia** [comment]
@pkoch this PR is dependant on #130. Once that one is merged, the conflicts should disappear.
They're just here because I have the base set to master

**Comment by nunopolonia** [comment]
@pkoch forget everything I said in the previously comment 😛 
I'll take care of the conflicts once `clean-controllers` is merged

**Comment by pkoch** [comment]
Roger! I'll look at this then.

**Comment by nunopolonia** [comment]
Rebasing with the updated master resolved the issues 😃

**Pull request closed without merging**
